### PR TITLE
add netstandard2.0 support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Rerago** [comment]
@Crauzer Would you merge the PR if possible (or not as you prefer). Then I could delete my fork.

**Comment by Rerago** [comment]
@Crauzer .net 5 is now EOL (08 May 2022). Would be a good reason to switch to 6.0 and release a new nuget or?

**Comment by ghost** [comment]
I still have one question. Is `System.Memory`, apart from `netstandard2.0`, necessary at all?

Because otherwise I could set the condition directly to the ItemGroup. Like this:

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
  <PackageReference Include="System.Memory" Version="4.5.4" />
  <PackageReference Include="IndexRange" Version="1.0.2" />
</ItemGroup>
```
This would in turn reduce dependencies on the other TargetFrameworks.

**Comment by Crauzer** [comment]
> I still have one question. Is `System.Memory`, apart from `netstandard2.0`, necessary at all?
> 
> Because otherwise I could set the condition directly to the ItemGroup. Like this:
> 
> ```
> <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
>   <PackageReference Include="System.Memory" Version="4.5.4" />
>   <PackageReference Include="IndexRange" Version="1.0.2" />
> </ItemGroup>
> ```
> 
> This would in turn reduce dependencies on the other TargetFrameworks.

`System.Memory` is only included from .NET Standard 2.1 onwards, so we'll have to include it as a dependency for .NET Standard 2.0.

**Comment by ghost** [comment]
That is exactly what I mean. In the [source file](https://github.com/Crauzer/XXHash3.NET/blob/main/XXHash3.NET/XXHash3.NET.csproj) you include it even though all ´TargetFrameworks´ do not require it. Hence the question.

But ok, if I understand you correctly you are my opinion. Then I still adjust that.

**Review by Crauzer — APPROVED** [review]

**Pull request merged**
